<div class="all-categories">
    <dl>
        <dt><?php echo Mage::helper('catalog/category')->__('Categories') ?>:</dt>
        <dd>
            <ul>
            <?php foreach($this->getAllCategories() as $category): ?>
                <li><a href="<?php echo $category->getUrl() ?>"><?php echo $category->getName(); ?></a></li>
            <?php endforeach; ?>
            </ul>
        </dd>
    </dl>
</div>